;
; File generated by cc65 v 2.19 - Git ed9f9cc
;
	.fopt		compiler,"cc65 v 2.19 - Git ed9f9cc"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_clrscr
	.import		_cputsxy
	.import		_VGMPlay_FTDI2XX_DIRECT
	.export		_port4016
	.export		_port4017
	.export		_main

.segment	"DATA"

_port4016:
	.word	$4016
_port4017:
	.word	$4017

.segment	"RODATA"

S0003:
	.byte	$2A,$50,$4C,$45,$41,$53,$45,$20,$52,$45,$53,$45,$54,$20,$41,$46
	.byte	$54,$45,$52,$20,$52,$45,$43,$4F,$4E,$4E,$45,$43,$54,$45,$44,$00
S0001:
	.byte	$4D,$41,$4D,$49,$20,$56,$47,$4D,$20,$53,$4F,$55,$4E,$44,$20,$44
	.byte	$52,$49,$56,$45,$52,$20,$42,$59,$20,$49,$54,$4F,$4B,$45,$4E,$00
S0004:
	.byte	$20,$31,$20,$20,$34,$35,$36,$37,$20,$2D,$3E,$20,$47,$4E,$44,$2C
	.byte	$43,$54,$53,$2C,$52,$54,$53,$2C,$52,$58,$2C,$54,$58,$00
S0002:
	.byte	$46,$54,$44,$49,$32,$58,$58,$20,$4D,$4F,$44,$45,$20,$52,$45,$41
	.byte	$44,$59,$20,$54,$4F,$20,$50,$4C,$41,$59,$2E,$00
S0009:
	.byte	$20,$20,$20,$20,$20,$31,$33,$20,$2D,$3E,$20,$20,$44,$54,$52,$00
S0007:
	.byte	$20,$5C,$6F,$6F,$6F,$6F,$2A,$6F,$6F,$2F,$20,$00
S0008:
	.byte	$20,$20,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$20,$20,$00
S0006:
	.byte	$5C,$2A,$6F,$6F,$2A,$2A,$2A,$2A,$6F,$20,$2F,$00
S0005:
	.byte	$5F,$5F,$5F,$5F,$5F,$5F,$5F,$5F,$5F,$5F,$5F,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _clrscr
	lda     #$00
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$05
	jsr     pusha
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$06
	jsr     pusha
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #<(S0007)
	ldx     #>(S0007)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$09
	jsr     pusha
	lda     #<(S0008)
	ldx     #>(S0008)
	jsr     _cputsxy
	lda     #$00
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #<(S0009)
	ldx     #>(S0009)
	jsr     _cputsxy
	jsr     _waitvsync
	jmp     L0004
L0002:	jsr     _VGMPlay_FTDI2XX_DIRECT
L0004:	jmp     L0002
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

