//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zanac.VGMPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DCSG_IF {
            get {
                return ((int)(this["DCSG_IF"]));
            }
            set {
                this["DCSG_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DCSG_Port {
            get {
                return ((int)(this["DCSG_Port"]));
            }
            set {
                this["DCSG_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_Port {
            get {
                return ((int)(this["OPLL_Port"]));
            }
            set {
                this["OPLL_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPN2_Port {
            get {
                return ((int)(this["OPN2_Port"]));
            }
            set {
                this["OPN2_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Loop {
            get {
                return ((bool)(this["Loop"]));
            }
            set {
                this["Loop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_IF {
            get {
                return ((int)(this["OPLL_IF"]));
            }
            set {
                this["OPLL_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPN2_IF {
            get {
                return ((int)(this["OPN2_IF"]));
            }
            set {
                this["OPN2_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPLL_Enable {
            get {
                return ((bool)(this["OPLL_Enable"]));
            }
            set {
                this["OPLL_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPN2_Enable {
            get {
                return ((bool)(this["OPN2_Enable"]));
            }
            set {
                this["OPN2_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DCSG_Enable {
            get {
                return ((bool)(this["DCSG_Enable"]));
            }
            set {
                this["DCSG_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Files {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Files"]));
            }
            set {
                this["Files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal BitBangWaitDCSG {
            get {
                return ((decimal)(this["BitBangWaitDCSG"]));
            }
            set {
                this["BitBangWaitDCSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FocusedItem {
            get {
                return ((int)(this["FocusedItem"]));
            }
            set {
                this["FocusedItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66000")]
        public decimal VGMWait {
            get {
                return ((decimal)(this["VGMWait"]));
            }
            set {
                this["VGMWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir {
            get {
                return ((string)(this["LastDir"]));
            }
            set {
                this["LastDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_IF {
            get {
                return ((int)(this["SCC_IF"]));
            }
            set {
                this["SCC_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SCC_Enable {
            get {
                return ((bool)(this["SCC_Enable"]));
            }
            set {
                this["SCC_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal BitBangWaitOPN2 {
            get {
                return ((decimal)(this["BitBangWaitOPN2"]));
            }
            set {
                this["BitBangWaitOPN2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitOPLL {
            get {
                return ((decimal)(this["BitBangWaitOPLL"]));
            }
            set {
                this["BitBangWaitOPLL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitSCC {
            get {
                return ((decimal)(this["BitBangWaitSCC"]));
            }
            set {
                this["BitBangWaitSCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitAY8910 {
            get {
                return ((decimal)(this["BitBangWaitAY8910"]));
            }
            set {
                this["BitBangWaitAY8910"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8910_IF {
            get {
                return ((int)(this["Y8910_IF"]));
            }
            set {
                this["Y8910_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Y8910_Enable {
            get {
                return ((bool)(this["Y8910_Enable"]));
            }
            set {
                this["Y8910_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Port {
            get {
                return ((int)(this["SCC_Port"]));
            }
            set {
                this["SCC_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8910_Port {
            get {
                return ((int)(this["Y8910_Port"]));
            }
            set {
                this["Y8910_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Slot {
            get {
                return ((int)(this["SCC_Slot"]));
            }
            set {
                this["SCC_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal KSS_Max {
            get {
                return ((decimal)(this["KSS_Max"]));
            }
            set {
                this["KSS_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Type {
            get {
                return ((int)(this["SCC_Type"]));
            }
            set {
                this["SCC_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_Port {
            get {
                return ((int)(this["OPM_Port"]));
            }
            set {
                this["OPM_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitOPM {
            get {
                return ((decimal)(this["BitBangWaitOPM"]));
            }
            set {
                this["BitBangWaitOPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPM_Enable {
            get {
                return ((bool)(this["OPM_Enable"]));
            }
            set {
                this["OPM_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_IF {
            get {
                return ((int)(this["OPM_IF"]));
            }
            set {
                this["OPM_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_Slot {
            get {
                return ((int)(this["OPM_Slot"]));
            }
            set {
                this["OPM_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_Slot {
            get {
                return ((int)(this["OPLL_Slot"]));
            }
            set {
                this["OPLL_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_IF {
            get {
                return ((int)(this["OPL3_IF"]));
            }
            set {
                this["OPL3_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPL3_Enable {
            get {
                return ((bool)(this["OPL3_Enable"]));
            }
            set {
                this["OPL3_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_Slot {
            get {
                return ((int)(this["OPL3_Slot"]));
            }
            set {
                this["OPL3_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_Port {
            get {
                return ((int)(this["OPL3_Port"]));
            }
            set {
                this["OPL3_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitOPL3 {
            get {
                return ((decimal)(this["BitBangWaitOPL3"]));
            }
            set {
                this["BitBangWaitOPL3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_IF {
            get {
                return ((int)(this["OPNA_IF"]));
            }
            set {
                this["OPNA_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPNA_Enable {
            get {
                return ((bool)(this["OPNA_Enable"]));
            }
            set {
                this["OPNA_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_Slot {
            get {
                return ((int)(this["OPNA_Slot"]));
            }
            set {
                this["OPNA_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_Port {
            get {
                return ((int)(this["OPNA_Port"]));
            }
            set {
                this["OPNA_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitOPNA {
            get {
                return ((decimal)(this["BitBangWaitOPNA"]));
            }
            set {
                this["BitBangWaitOPNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_IF {
            get {
                return ((int)(this["Y8950_IF"]));
            }
            set {
                this["Y8950_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Y8950_Enable {
            get {
                return ((bool)(this["Y8950_Enable"]));
            }
            set {
                this["Y8950_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Slot {
            get {
                return ((int)(this["Y8950_Slot"]));
            }
            set {
                this["Y8950_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Port {
            get {
                return ((int)(this["Y8950_Port"]));
            }
            set {
                this["Y8950_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitY8950 {
            get {
                return ((decimal)(this["BitBangWaitY8950"]));
            }
            set {
                this["BitBangWaitY8950"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Type {
            get {
                return ((int)(this["Y8950_Type"]));
            }
            set {
                this["Y8950_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LoopCount {
            get {
                return ((decimal)(this["LoopCount"]));
            }
            set {
                this["LoopCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoopTime {
            get {
                return ((bool)(this["LoopTime"]));
            }
            set {
                this["LoopTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/1753 00:05:00")]
        public global::System.DateTime LoopTimes {
            get {
                return ((global::System.DateTime)(this["LoopTimes"]));
            }
            set {
                this["LoopTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertClock {
            get {
                return ((bool)(this["ConvertClock"]));
            }
            set {
                this["ConvertClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPN_IF {
            get {
                return ((int)(this["OPN_IF"]));
            }
            set {
                this["OPN_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPN_Enable {
            get {
                return ((bool)(this["OPN_Enable"]));
            }
            set {
                this["OPN_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPN_Slot {
            get {
                return ((int)(this["OPN_Slot"]));
            }
            set {
                this["OPN_Slot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPN_Port {
            get {
                return ((int)(this["OPN_Port"]));
            }
            set {
                this["OPN_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitOPN {
            get {
                return ((decimal)(this["BitBangWaitOPN"]));
            }
            set {
                this["BitBangWaitOPN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPN2Div {
            get {
                return ((decimal)(this["OPN2Div"]));
            }
            set {
                this["OPN2Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DCSGDiv {
            get {
                return ((decimal)(this["DCSGDiv"]));
            }
            set {
                this["DCSGDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPLLDiv {
            get {
                return ((decimal)(this["OPLLDiv"]));
            }
            set {
                this["OPLLDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal SCCDiv {
            get {
                return ((decimal)(this["SCCDiv"]));
            }
            set {
                this["SCCDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal PSGDiv {
            get {
                return ((decimal)(this["PSGDiv"]));
            }
            set {
                this["PSGDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPMDiv {
            get {
                return ((decimal)(this["OPMDiv"]));
            }
            set {
                this["OPMDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPL3Div {
            get {
                return ((decimal)(this["OPL3Div"]));
            }
            set {
                this["OPL3Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPNADiv {
            get {
                return ((decimal)(this["OPNADiv"]));
            }
            set {
                this["OPNADiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal Y8950Div {
            get {
                return ((decimal)(this["Y8950Div"]));
            }
            set {
                this["Y8950Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OPNDiv {
            get {
                return ((decimal)(this["OPNDiv"]));
            }
            set {
                this["OPNDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("759, 200")]
        public global::System.Drawing.Size PaneHeight {
            get {
                return ((global::System.Drawing.Size)(this["PaneHeight"]));
            }
            set {
                this["PaneHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableDAC {
            get {
                return ((bool)(this["DisableDAC"]));
            }
            set {
                this["DisableDAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal DacVolume {
            get {
                return ((decimal)(this["DacVolume"]));
            }
            set {
                this["DacVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SegaPcmRate {
            get {
                return ((int)(this["SegaPcmRate"]));
            }
            set {
                this["SegaPcmRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int K053260Rate {
            get {
                return ((int)(this["K053260Rate"]));
            }
            set {
                this["K053260Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OKIM6295Rate {
            get {
                return ((int)(this["OKIM6295Rate"]));
            }
            set {
                this["OKIM6295Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NES_IF {
            get {
                return ((int)(this["NES_IF"]));
            }
            set {
                this["NES_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NES_Enable {
            get {
                return ((bool)(this["NES_Enable"]));
            }
            set {
                this["NES_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal NESDiv {
            get {
                return ((decimal)(this["NESDiv"]));
            }
            set {
                this["NESDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NES_Port {
            get {
                return ((int)(this["NES_Port"]));
            }
            set {
                this["NES_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public decimal BitBangWaitNES {
            get {
                return ((decimal)(this["BitBangWaitNES"]));
            }
            set {
                this["BitBangWaitNES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NesDpcmRate {
            get {
                return ((int)(this["NesDpcmRate"]));
            }
            set {
                this["NesDpcmRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MCD_Enable {
            get {
                return ((bool)(this["MCD_Enable"]));
            }
            set {
                this["MCD_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MCD_IF {
            get {
                return ((int)(this["MCD_IF"]));
            }
            set {
                this["MCD_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MCD_Port {
            get {
                return ((int)(this["MCD_Port"]));
            }
            set {
                this["MCD_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal MCD_Div {
            get {
                return ((decimal)(this["MCD_Div"]));
            }
            set {
                this["MCD_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal BitBangWaitMCD {
            get {
                return ((decimal)(this["BitBangWaitMCD"]));
            }
            set {
                this["BitBangWaitMCD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PlaybackSpeed {
            get {
                return ((double)(this["PlaybackSpeed"]));
            }
            set {
                this["PlaybackSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAA_Enable {
            get {
                return ((bool)(this["SAA_Enable"]));
            }
            set {
                this["SAA_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SAA_IF {
            get {
                return ((int)(this["SAA_IF"]));
            }
            set {
                this["SAA_IF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SAA_Port {
            get {
                return ((int)(this["SAA_Port"]));
            }
            set {
                this["SAA_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal SAA_Div {
            get {
                return ((decimal)(this["SAA_Div"]));
            }
            set {
                this["SAA_Div"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal BitBangWaitSAA {
            get {
                return ((decimal)(this["BitBangWaitSAA"]));
            }
            set {
                this["BitBangWaitSAA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WaitAlg {
            get {
                return ((int)(this["WaitAlg"]));
            }
            set {
                this["WaitAlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DACClipping {
            get {
                return ((bool)(this["DACClipping"]));
            }
            set {
                this["DACClipping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCoverArt {
            get {
                return ((bool)(this["ShowCoverArt"]));
            }
            set {
                this["ShowCoverArt"] = value;
            }
        }
    }
}
