//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jacobi.Vst.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jacobi.Vst.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The property is already set to an instance of an object. Reset to null before assigning a new object instance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensibleInterfaceRef_InstanceAlreadySet {
            get {
                return ResourceManager.GetString("ExtensibleInterfaceRef_InstanceAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Host does not implement OpenFileSelector. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelectorScope_OpenNotSupported {
            get {
                return ResourceManager.GetString("FileSelectorScope_OpenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The HostCommandStub has not been initialized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StdPluginCommandStub_HostNotInitialized {
            get {
                return ResourceManager.GetString("StdPluginCommandStub_HostNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Plugin returned a {0} &apos;{1}&apos; that is too long. Maximum length is {2} characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StdPluginCommandStub_StringTooLong {
            get {
                return ResourceManager.GetString("StdPluginCommandStub_StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The VstEventCollection is read-only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VstEventCollection_CollectionReadOnly {
            get {
                return ResourceManager.GetString("VstEventCollection_CollectionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigned VstParameterManager value is not linked to this VstParamaterInfo instance. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VstParameterInfo_ParameterManagerNotLinked {
            get {
                return ResourceManager.GetString("VstParameterInfo_ParameterManagerNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified VstParameterInfo instance already has a VstParameterNormalizationInfo instance attached. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VstParameterNormalizationInfo_AlreadyAttached {
            get {
                return ResourceManager.GetString("VstParameterNormalizationInfo_AlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified VstParameterInfo does not have a valid value range set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VstParameterNormalizationInfo_ParameterInfoInvalid {
            get {
                return ResourceManager.GetString("VstParameterNormalizationInfo_ParameterInfoInvalid", resourceCulture);
            }
        }
    }
}
