// copyright-holders:K.Ito
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing.Design;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using zanac.MAmidiMEmo.ComponentModel;

namespace zanac.MAmidiMEmo.Midi
{
    [Editor(typeof(EnumTypeEditor), typeof(UITypeEditor))]
    [TypeConverter(typeof(EnumConverter<NoteNames>))]
    public enum NoteNames : byte
    {
        [Description("C-1")]
        C_1,
        [Description("C#-1")]
        CS_1,
        [Description("D-1")]
        D_1,
        [Description("D#-1")]
        DS_1,
        [Description("E-1")]
        E_1,
        [Description("F-1")]
        F_1,
        [Description("G-1")]
        G_1,
        [Description("G#-1")]
        GS_1,
        [Description("A-1")]
        A_1,
        [Description("A#-1")]
        AS_1,
        [Description("B-1")]
        B_1,

        [Description("C0")]
        C0,
        [Description("C#0")]
        CS0,
        [Description("D0")]
        D0,
        [Description("D#0")]
        DS0,
        [Description("E0")]
        E0,
        [Description("F0")]
        F0,
        [Description("G0")]
        G0,
        [Description("G#0")]
        GS0,
        [Description("A0")]
        A0,
        [Description("A#0")]
        AS0,
        [Description("B0")]
        B0,

        [Description("C1")]
        C1,
        [Description("C#1")]
        CS1,
        [Description("D1")]
        D1,
        [Description("D#1")]
        DS1,
        [Description("E1")]
        E1,
        [Description("F1")]
        F1,
        [Description("G1")]
        G1,
        [Description("G#1")]
        GS1,
        [Description("A1")]
        A1,
        [Description("A#1")]
        AS1,
        [Description("B1")]
        B1,

        [Description("C2")]
        C2,
        [Description("C#2")]
        CS2,
        [Description("D2")]
        D2,
        [Description("D#2")]
        DS2,
        [Description("E2")]
        E2,
        [Description("F2")]
        F2,
        [Description("G2")]
        G2,
        [Description("G#2")]
        GS2,
        [Description("A2")]
        A2,
        [Description("A#2")]
        AS2,
        [Description("B2")]
        B2,

        [Description("C3")]
        C3,
        [Description("C#3")]
        CS3,
        [Description("D3")]
        D3,
        [Description("D#3")]
        DS3,
        [Description("E3")]
        E3,
        [Description("F3")]
        F3,
        [Description("G3")]
        G3,
        [Description("G#3")]
        GS3,
        [Description("A3")]
        A3,
        [Description("A#3")]
        AS3,
        [Description("B3")]
        B3,

        [Description("C4")]
        C4,
        [Description("C#4")]
        CS4,
        [Description("D4")]
        D4,
        [Description("D#4")]
        DS4,
        [Description("E4")]
        E4,
        [Description("F4")]
        F4,
        [Description("G4")]
        G4,
        [Description("G#4")]
        GS4,
        [Description("A4")]
        A4,
        [Description("A#4")]
        AS4,
        [Description("B4")]
        B4,


        [Description("C5")]
        C5,
        [Description("C#5")]
        CS5,
        [Description("D5")]
        D5,
        [Description("D#5")]
        DS5,
        [Description("E5")]
        E5,
        [Description("F5")]
        F5,
        [Description("G5")]
        G5,
        [Description("G#5")]
        GS5,
        [Description("A5")]
        A5,
        [Description("A#5")]
        AS5,
        [Description("B5")]
        B5,

        [Description("C6")]
        C6,
        [Description("C#6")]
        CS6,
        [Description("D6")]
        D6,
        [Description("D#6")]
        DS6,
        [Description("E6")]
        E6,
        [Description("F6")]
        F6,
        [Description("G6")]
        G6,
        [Description("G#6")]
        GS6,
        [Description("A6")]
        A6,
        [Description("A#6")]
        AS6,
        [Description("B6")]
        B6,

        [Description("C7")]
        C7,
        [Description("C#7")]
        CS7,
        [Description("D7")]
        D7,
        [Description("D#7")]
        DS7,
        [Description("E7")]
        E7,
        [Description("F7")]
        F7,
        [Description("G7")]
        G7,
        [Description("G#7")]
        GS7,
        [Description("A7")]
        A7,
        [Description("A#7")]
        AS7,
        [Description("B7")]
        B7,

        [Description("C8")]
        C8,
        [Description("C#8")]
        CS8,
        [Description("D8")]
        D8,
        [Description("D#8")]
        DS8,
        [Description("E8")]
        E8,
        [Description("F8")]
        F8,
        [Description("G8")]
        G8,
        [Description("G#8")]
        GS8,
        [Description("A8")]
        A8,
        [Description("A#8")]
        AS8,
        [Description("B8")]
        B8,

        [Description("C9")]
        C9,
        [Description("C#9")]
        CS9,
        [Description("D9")]
        D9,
        [Description("D#9")]
        DS9,
        [Description("E9")]
        E9,
        [Description("F9")]
        F9,
        [Description("G9")]
        G9,
    }
}
