//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zanac.VGMPlayer
{

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DCSG_IF
        {
            get
            {
                return ((int)(this["DCSG_IF"]));
            }
            set
            {
                this["DCSG_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DCSG_Port
        {
            get
            {
                return ((int)(this["DCSG_Port"]));
            }
            set
            {
                this["DCSG_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_Port
        {
            get
            {
                return ((int)(this["OPLL_Port"]));
            }
            set
            {
                this["OPLL_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA2_Port
        {
            get
            {
                return ((int)(this["OPNA2_Port"]));
            }
            set
            {
                this["OPNA2_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Loop
        {
            get
            {
                return ((bool)(this["Loop"]));
            }
            set
            {
                this["Loop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_IF
        {
            get
            {
                return ((int)(this["OPLL_IF"]));
            }
            set
            {
                this["OPLL_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA2_IF
        {
            get
            {
                return ((int)(this["OPNA2_IF"]));
            }
            set
            {
                this["OPNA2_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPLL_Enable
        {
            get
            {
                return ((bool)(this["OPLL_Enable"]));
            }
            set
            {
                this["OPLL_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPNA2_Enable
        {
            get
            {
                return ((bool)(this["OPNA2_Enable"]));
            }
            set
            {
                this["OPNA2_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DCSG_Enable
        {
            get
            {
                return ((bool)(this["DCSG_Enable"]));
            }
            set
            {
                this["DCSG_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Files
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["Files"]));
            }
            set
            {
                this["Files"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal BitBangWaitDCSG
        {
            get
            {
                return ((decimal)(this["BitBangWaitDCSG"]));
            }
            set
            {
                this["BitBangWaitDCSG"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FocusedItem
        {
            get
            {
                return ((int)(this["FocusedItem"]));
            }
            set
            {
                this["FocusedItem"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal VGMWait
        {
            get
            {
                return ((decimal)(this["VGMWait"]));
            }
            set
            {
                this["VGMWait"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDir
        {
            get
            {
                return ((string)(this["LastDir"]));
            }
            set
            {
                this["LastDir"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_IF
        {
            get
            {
                return ((int)(this["SCC_IF"]));
            }
            set
            {
                this["SCC_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SCC_Enable
        {
            get
            {
                return ((bool)(this["SCC_Enable"]));
            }
            set
            {
                this["SCC_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal BitBangWaitOPNA2
        {
            get
            {
                return ((decimal)(this["BitBangWaitOPNA2"]));
            }
            set
            {
                this["BitBangWaitOPNA2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitOPLL
        {
            get
            {
                return ((decimal)(this["BitBangWaitOPLL"]));
            }
            set
            {
                this["BitBangWaitOPLL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitSCC
        {
            get
            {
                return ((decimal)(this["BitBangWaitSCC"]));
            }
            set
            {
                this["BitBangWaitSCC"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitAY8910
        {
            get
            {
                return ((decimal)(this["BitBangWaitAY8910"]));
            }
            set
            {
                this["BitBangWaitAY8910"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8910_IF
        {
            get
            {
                return ((int)(this["Y8910_IF"]));
            }
            set
            {
                this["Y8910_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Y8910_Enable
        {
            get
            {
                return ((bool)(this["Y8910_Enable"]));
            }
            set
            {
                this["Y8910_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Port
        {
            get
            {
                return ((int)(this["SCC_Port"]));
            }
            set
            {
                this["SCC_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8910_Port
        {
            get
            {
                return ((int)(this["Y8910_Port"]));
            }
            set
            {
                this["Y8910_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Slot
        {
            get
            {
                return ((int)(this["SCC_Slot"]));
            }
            set
            {
                this["SCC_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public decimal KSS_Max
        {
            get
            {
                return ((decimal)(this["KSS_Max"]));
            }
            set
            {
                this["KSS_Max"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SCC_Type
        {
            get
            {
                return ((int)(this["SCC_Type"]));
            }
            set
            {
                this["SCC_Type"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_Port
        {
            get
            {
                return ((int)(this["OPM_Port"]));
            }
            set
            {
                this["OPM_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitOPM
        {
            get
            {
                return ((decimal)(this["BitBangWaitOPM"]));
            }
            set
            {
                this["BitBangWaitOPM"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPM_Enable
        {
            get
            {
                return ((bool)(this["OPM_Enable"]));
            }
            set
            {
                this["OPM_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_IF
        {
            get
            {
                return ((int)(this["OPM_IF"]));
            }
            set
            {
                this["OPM_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPM_Slot
        {
            get
            {
                return ((int)(this["OPM_Slot"]));
            }
            set
            {
                this["OPM_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPLL_Slot
        {
            get
            {
                return ((int)(this["OPLL_Slot"]));
            }
            set
            {
                this["OPLL_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_IF
        {
            get
            {
                return ((int)(this["OPL3_IF"]));
            }
            set
            {
                this["OPL3_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPL3_Enable
        {
            get
            {
                return ((bool)(this["OPL3_Enable"]));
            }
            set
            {
                this["OPL3_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_Slot
        {
            get
            {
                return ((int)(this["OPL3_Slot"]));
            }
            set
            {
                this["OPL3_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPL3_Port
        {
            get
            {
                return ((int)(this["OPL3_Port"]));
            }
            set
            {
                this["OPL3_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitOPL3
        {
            get
            {
                return ((decimal)(this["BitBangWaitOPL3"]));
            }
            set
            {
                this["BitBangWaitOPL3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_IF
        {
            get
            {
                return ((int)(this["OPNA_IF"]));
            }
            set
            {
                this["OPNA_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OPNA_Enable
        {
            get
            {
                return ((bool)(this["OPNA_Enable"]));
            }
            set
            {
                this["OPNA_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_Slot
        {
            get
            {
                return ((int)(this["OPNA_Slot"]));
            }
            set
            {
                this["OPNA_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OPNA_Port
        {
            get
            {
                return ((int)(this["OPNA_Port"]));
            }
            set
            {
                this["OPNA_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitOPNA
        {
            get
            {
                return ((decimal)(this["BitBangWaitOPNA"]));
            }
            set
            {
                this["BitBangWaitOPNA"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_IF
        {
            get
            {
                return ((int)(this["Y8950_IF"]));
            }
            set
            {
                this["Y8950_IF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Y8950_Enable
        {
            get
            {
                return ((bool)(this["Y8950_Enable"]));
            }
            set
            {
                this["Y8950_Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Slot
        {
            get
            {
                return ((int)(this["Y8950_Slot"]));
            }
            set
            {
                this["Y8950_Slot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Port
        {
            get
            {
                return ((int)(this["Y8950_Port"]));
            }
            set
            {
                this["Y8950_Port"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public decimal BitBangWaitY8950
        {
            get
            {
                return ((decimal)(this["BitBangWaitY8950"]));
            }
            set
            {
                this["BitBangWaitY8950"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Y8950_Type
        {
            get
            {
                return ((int)(this["Y8950_Type"]));
            }
            set
            {
                this["Y8950_Type"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LoopCount
        {
            get
            {
                return ((decimal)(this["LoopCount"]));
            }
            set
            {
                this["LoopCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoopTime
        {
            get
            {
                return ((bool)(this["LoopTime"]));
            }
            set
            {
                this["LoopTime"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/1753 00:05:00")]
        public global::System.DateTime LoopTimes
        {
            get
            {
                return ((global::System.DateTime)(this["LoopTimes"]));
            }
            set
            {
                this["LoopTimes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertClock
        {
            get
            {
                return ((bool)(this["ConvertClock"]));
            }
            set
            {
                this["ConvertClock"] = value;
            }
        }
    }
}
