//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zanac.MAmidiMEmo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zanac.MAmidiMEmo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ADPCM buffer exceeded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdpcmBufferExceeded {
            get {
                return ResourceManager.GetString("AdpcmBufferExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADPCM buffer used {0}/256 KB. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdpcmBufferUsed {
            get {
                return ResourceManager.GetString("AdpcmBufferUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADPCM buffer used {0}/63 KB. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdpcmBufferUsedSPC700 {
            get {
                return ResourceManager.GetString("AdpcmBufferUsedSPC700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG1 {
            get {
                object obj = ResourceManager.GetObject("ALG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG10 {
            get {
                object obj = ResourceManager.GetObject("ALG10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG11 {
            get {
                object obj = ResourceManager.GetObject("ALG11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG12 {
            get {
                object obj = ResourceManager.GetObject("ALG12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG2 {
            get {
                object obj = ResourceManager.GetObject("ALG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG3 {
            get {
                object obj = ResourceManager.GetObject("ALG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG4 {
            get {
                object obj = ResourceManager.GetObject("ALG4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG5 {
            get {
                object obj = ResourceManager.GetObject("ALG5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG5Q {
            get {
                object obj = ResourceManager.GetObject("ALG5Q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG6 {
            get {
                object obj = ResourceManager.GetObject("ALG6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG7 {
            get {
                object obj = ResourceManager.GetObject("ALG7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG8 {
            get {
                object obj = ResourceManager.GetObject("ALG8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG8Q {
            get {
                object obj = ResourceManager.GetObject("ALG8Q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ALG9 {
            get {
                object obj = ResourceManager.GetObject("ALG9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AllProp {
            get {
                object obj = ResourceManager.GetObject("AllProp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AtoZ {
            get {
                object obj = ResourceManager.GetObject("AtoZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AY_3_8910 {
            get {
                object obj = ResourceManager.GetObject("AY_3_8910", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Beep {
            get {
                object obj = ResourceManager.GetObject("Beep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap C140 {
            get {
                object obj = ResourceManager.GetObject("C140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Cat {
            get {
                object obj = ResourceManager.GetObject("Cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Chip {
            get {
                object obj = ResourceManager.GetObject("Chip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Do you clear all instruments? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearAllInsts {
            get {
                return ResourceManager.GetString("ClearAllInsts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CM32P {
            get {
                object obj = ResourceManager.GetObject("CM32P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ;;; # CMUdict  --  Major Version: 0.07
        ///;;; 
        ///;;; # $HeadURL$
        ///;;; # $Date::                                                   $:
        ///;;; # $Id::                                                     $:
        ///;;; # $Rev::                                                    $: 
        ///;;; # $Author::                                                 $:
        ///;;;
        ///;;; #
        ///;;; # ========================================================================
        ///;;; # Copyright (C) 1993-2015 Carnegie Mellon University. All rights reserved.
        ///;;;  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmudict_0_7b {
            get {
                return ResourceManager.GetString("cmudict_0_7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should Chip(Global) -&gt; CONSEL prop value to 1 or higher value to sound 4 operator sound. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNTWarning {
            get {
                return ResourceManager.GetString("CNTWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to convert sample rate to {0}Hz?
        ///(Selection is memorized. Reboot or hold down the Alt key while selecting a file to reconfirm) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmConvertSampleRate {
            get {
                return ResourceManager.GetString("ConfirmConvertSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to a real chip via c86ctl for GIMIC... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectingGimic {
            get {
                return ResourceManager.GetString("ConnectingGimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to a real chip via SCCI... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectingSPFM {
            get {
                return ResourceManager.GetString("ConnectingSPFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the number to be sequentially numbered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContinuousSet {
            get {
                return ResourceManager.GetString("ContinuousSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the item for which the TimbreNumber has been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContinuousSetError {
            get {
                return ResourceManager.GetString("ContinuousSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAmi VSTi was copied to the DAW plugins folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopiedVSTi {
            get {
                return ResourceManager.GetString("CopiedVSTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap donate {
            get {
                object obj = ResourceManager.GetObject("donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DPCM buffer exceeded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DpcmBufferExceeded {
            get {
                return ResourceManager.GetString("DpcmBufferExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DPCM buffer used {0} bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DpcmBufferUsed {
            get {
                return ResourceManager.GetString("DpcmBufferUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] DSEG14ClassicMini_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("DSEG14ClassicMini_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] DSEG7ClassicMini_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("DSEG7ClassicMini_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Failed to launch. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedLaunch {
            get {
                return ResourceManager.GetString("FailedLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedLoadFile {
            get {
                return ResourceManager.GetString("FailedLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the MAmi file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedLoadMAmi {
            get {
                return ResourceManager.GetString("FailedLoadMAmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the MAmidi file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedLoadMAmidi {
            get {
                return ResourceManager.GetString("FailedLoadMAmidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load the MIDI file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedLoadMidi {
            get {
                return ResourceManager.GetString("FailedLoadMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to set MIDI I/F. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedMidiIf {
            get {
                return ResourceManager.GetString("FailedMidiIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the current env. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedSaveEnv {
            get {
                return ResourceManager.GetString("FailedSaveEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the current env and midi into the MAmidi file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedSaveMAmidi {
            get {
                return ResourceManager.GetString("FailedSaveMAmidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GB_APU {
            get {
                object obj = ResourceManager.GetObject("GB_APU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap General {
            get {
                object obj = ResourceManager.GetObject("General", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap HuC6280 {
            get {
                object obj = ResourceManager.GetObject("HuC6280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Import PCM from SF2 for &amp;DrumTimbres... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportSF2Drum {
            get {
                return ResourceManager.GetString("ImportSF2Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import PCM from SF2 for &amp;Timbres... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportSF2Timbre {
            get {
                return ResourceManager.GetString("ImportSF2Timbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import PCM from S&amp;PC for DrumTimbres... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportSpcDrum {
            get {
                return ResourceManager.GetString("ImportSpcDrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import PCM from &amp;SPC for Timbres... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportSpcTimbre {
            get {
                return ResourceManager.GetString("ImportSpcTimbre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Inst {
            get {
                object obj = ResourceManager.GetObject("Inst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please load a midi file to save the current env and midi file into the MAmidi file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadMidiFile {
            get {
                return ResourceManager.GetString("LoadMidiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Midi {
            get {
                object obj = ResourceManager.GetObject("Midi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MIDITHRU {
            get {
                object obj = ResourceManager.GetObject("MIDITHRU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MOS6581 {
            get {
                object obj = ResourceManager.GetObject("MOS6581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MOS8580 {
            get {
                object obj = ResourceManager.GetObject("MOS8580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MSM5232 {
            get {
                object obj = ResourceManager.GetObject("MSM5232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MT32 {
            get {
                object obj = ResourceManager.GetObject("MT32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MultiPCM {
            get {
                object obj = ResourceManager.GetObject("MultiPCM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap NAMCO_CUS30 {
            get {
                object obj = ResourceManager.GetObject("NAMCO_CUS30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   There are no MIDI IN devices.
        ///Please install at least one MIDI IN device to use the MAmidiMEmo all functions.
        ///Or, install the loopMIDI application to the PC. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoMidiPort {
            get {
                return ResourceManager.GetString("NoMidiPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Panic {
            get {
                object obj = ResourceManager.GetObject("Panic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PAULA_8364 {
            get {
                object obj = ResourceManager.GetObject("PAULA_8364", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap TIA
        {
            get
            {
                object obj = ResourceManager.GetObject("TIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap VLM5030
        {
            get
            {
                object obj = ResourceManager.GetObject("VLM5030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] PixelMplus12_Regular {
            get {
                object obj = ResourceManager.GetObject("PixelMplus12_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap POKEY {
            get {
                object obj = ResourceManager.GetObject("POKEY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Popup {
            get {
                object obj = ResourceManager.GetObject("Popup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Prev {
            get {
                object obj = ResourceManager.GetObject("Prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Rec {
            get {
                object obj = ResourceManager.GetObject("Rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Do you restart to apply new settings? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestartConfirmation {
            get {
                return ResourceManager.GetString("RestartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap RF5C164 {
            get {
                object obj = ResourceManager.GetObject("RF5C164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap RP2A03 {
            get {
                object obj = ResourceManager.GetObject("RP2A03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Rst {
            get {
                object obj = ResourceManager.GetObject("Rst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SAA1099 {
            get {
                object obj = ResourceManager.GetObject("SAA1099", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SAM {
            get {
                object obj = ResourceManager.GetObject("SAM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   MAmi sample rate follows DAW sample rate at startup MAmi. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample rate is higher than {0}Hz. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleRateOver {
            get {
                return ResourceManager.GetString("SampleRateOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SCC1 {
            get {
                object obj = ResourceManager.GetObject("SCC1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please select a DAW plugins folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectDAWFolder {
            get {
                return ResourceManager.GetString("SelectDAWFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SN76477 {
            get {
                object obj = ResourceManager.GetObject("SN76477", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SN76496 {
            get {
                object obj = ResourceManager.GetObject("SN76496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SP0256 {
            get {
                object obj = ResourceManager.GetObject("SP0256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SPC700 {
            get {
                object obj = ResourceManager.GetObject("SPC700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Timbre {
            get {
                object obj = ResourceManager.GetObject("Timbre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Timbre &amp;List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimbreList {
            get {
                return ResourceManager.GetString("TimbreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} timbres loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimbreLoaded {
            get {
                return ResourceManager.GetString("TimbreLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap TMS5220 {
            get {
                object obj = ResourceManager.GetObject("TMS5220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap uPD1771C {
            get {
                object obj = ResourceManager.GetObject("uPD1771C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Updating ADPCM data... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatingADPCM {
            get {
                return ResourceManager.GetString("UpdatingADPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating DPCM data... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatingDPCM {
            get {
                return ResourceManager.GetString("UpdatingDPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating PCM data... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatingPCM {
            get {
                return ResourceManager.GetString("UpdatingPCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some sample loop length is not a multiple of 16.
        ///So, sound glitches may occur. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WanrSPC700SampleLength {
            get {
                return ResourceManager.GetString("WanrSPC700SampleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS0 {
            get {
                object obj = ResourceManager.GetObject("WS0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS1 {
            get {
                object obj = ResourceManager.GetObject("WS1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS10 {
            get {
                object obj = ResourceManager.GetObject("WS10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS11 {
            get {
                object obj = ResourceManager.GetObject("WS11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS2 {
            get {
                object obj = ResourceManager.GetObject("WS2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS3 {
            get {
                object obj = ResourceManager.GetObject("WS3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS4 {
            get {
                object obj = ResourceManager.GetObject("WS4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS5 {
            get {
                object obj = ResourceManager.GetObject("WS5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS6 {
            get {
                object obj = ResourceManager.GetObject("WS6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS7 {
            get {
                object obj = ResourceManager.GetObject("WS7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS8 {
            get {
                object obj = ResourceManager.GetObject("WS8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap WS9 {
            get {
                object obj = ResourceManager.GetObject("WS9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please select all items except the last one に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WsgMorphError1 {
            get {
                return ResourceManager.GetString("WsgMorphError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the number of items to be added に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WsgMorphTitle {
            get {
                return ResourceManager.GetString("WsgMorphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2151 {
            get {
                object obj = ResourceManager.GetObject("YM2151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2413 {
            get {
                object obj = ResourceManager.GetObject("YM2413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2414 {
            get {
                object obj = ResourceManager.GetObject("YM2414", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2608 {
            get {
                object obj = ResourceManager.GetObject("YM2608", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2610B {
            get {
                object obj = ResourceManager.GetObject("YM2610B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM2612 {
            get {
                object obj = ResourceManager.GetObject("YM2612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM3806 {
            get {
                object obj = ResourceManager.GetObject("YM3806", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YM3812 {
            get {
                object obj = ResourceManager.GetObject("YM3812", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap YMF262 {
            get {
                object obj = ResourceManager.GetObject("YMF262", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
